Minimize blocking in Filesystem.getCachedDiskUsage
schrej/wings.go pull request #53
Opened 2020-08-30 03:58 UTC by cyberkitsune

This resolves pterodactyl/panel#2287

When the disk size cache expires BUT another process is already refreshing it, just return the stale size instead of locking.

This prevents several other things (namely console updates) from freezing if the disk size process is taking ages.

I added an argument to skip the cache for some processes that we're ok with always blocking (like server startup)

2020-08-30 04:00 UTC, cyberkitsune commented
Don't merge quite yet, covering some additional bases. Feedback welcome still however

2020-08-30 04:20 UTC, cyberkitsune commented
This is behaving correctly for me now.

2020-08-30 16:12 UTC, DaneEveritt requested changes

2020-08-30 16:12 UTC, DaneEveritt commented on server/filesystem.go
> +	if !avoidCache && (fs.lastLookupTime.After(time.Now().Add(time.Second*-150)) || fs.lookupInProgress) {
The `avoidCache` check here is unnecessary and actually causes more problems because it will fall through to the `updateCachedDiskUsage()` call even if the value in the cache is still valid, right? This should also ideally explain why this logic even exists, since the lookup time is clear but the avoid cache and lookup in progress checks aren't as intuitive.

2020-08-30 16:12 UTC, DaneEveritt commented on server/filesystem.go
> +func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
I don't think `avoidCache` is a good variable name to describe what it is actually doing here. Perhaps `blockIfStale` or something? Ideally I'd prefer if it didn't even have a parameter being passed through, it feels like something we _should_ be able to check for on our own.

There is always the fun `(...block bool)` trick where we can default to `false` unless someone explicitly calls this with `true`. I'm just worried it is not going to be intuitive to people _how_ to call this function or when they should or should not be passing `true` or `false` if that makes sense.

2020-08-30 16:12 UTC, DaneEveritt commented on server/filesystem.go
> +	fs.lookupInProgress = false
For safety, this should probably be a deferred call up where it is set so if this function ever changes or manages to exit early down the road we don't forget to set this back to false.

2020-08-30 16:12 UTC, DaneEveritt commented on server/loader.go
> +		go s.Filesystem.HasSpaceAvailable(true)
This doesn't need to be `true`, it is "forcing" calculation simply so there is a value returned, it doesn't need to be the most accurate value. In this case, we can pass false and not even put this in a go-routine.

2020-08-30 16:12 UTC, DaneEveritt commented on server/filesystem.go
> +func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
Thinking about this more, I'd like if it blocked by default, and only was a non-blocking call in specific cases. Most all of the code was written around that assumption anyways, so making it blocking unless specifically called as a non-blocking operation would make the most sense.

2020-08-30 17:44 UTC, matthewpi requested changes

2020-08-30 17:44 UTC, matthewpi commented on server/filesystem.go
> +	lookupInProgress bool `default:"false"`
There is no need for the `default:"false"`, it doesn't do anything.  Also a `bool`'s default value is `false`.

2020-08-30 17:44 UTC, matthewpi commented on server/filesystem.go
>  	mu sync.RWMutex
This mutex doesn't seem to be used anywhere else, it could probably be switched to a `sync.Mutex`.

2020-08-30 17:44 UTC, matthewpi commented on server/filesystem.go
> +		return fs.diskUsage, nil
Use `atomic.LoadInt64` when working with `diskUsage` as it is set atomically.

2020-08-30 17:44 UTC, matthewpi commented on server/filesystem.go
> +	return fs.diskUsage, nil
Use `atomic.LoadInt64` when working with `diskUsage` as it is set atomically.

2020-08-30 17:44 UTC, matthewpi commented on server/filesystem.go
> +		return fs.diskUsage, nil
Also reading `fs.lookupInProgress` could cause a race condition as it is set with a lock but this function doesn't use one, it would probably be best to make it an atomic.

2020-08-30 21:00 UTC, cyberkitsune commented on server/filesystem.go
> +func (fs *Filesystem) getCachedDiskUsage(avoidCache bool) (int64, error) {
I renamed it to "nonBlocking" and described briefly why it exists in the function comments, would that work? :)

2020-09-01 03:25 UTC, DaneEveritt approved these changes

2020-09-01 03:27 UTC, merged