Added app name
schrej/wings.go pull request #88
Opened 2021-03-24 09:29 UTC by Antony1060

This just adds the ability for a bit more customization.

2021-03-24 10:23 UTC, schrej requested changes

2021-03-24 10:23 UTC, schrej commented on config/config.go
> +	AppName string `json:"app_name" yaml:"app_name"`
```suggestion
	AppName string `default:"Pterodactyl" json:"app_name" yaml:"app_name"`
```

2021-03-24 10:28 UTC, schrej approved these changes

2021-03-31 06:26 UTC, ririko5834 commented
When this will be added?

2021-04-01 19:33 UTC, FoksVHox commented
> When this will be added?

It doesn't help to comment "When will this be added", "any update". Only comment if you've anything relating to the PR. 

@Antony1060 What's up with the failing test?

2021-04-01 19:58 UTC, Antony1060 commented
> What's up with the failing test?

That test seems to fail on all of the other PRs. I don't think I can do anything about that.

2021-04-03 18:13 UTC, merged

2021-04-04 15:45 UTC, hwalker928 commented
Shouldn't the default be "Pterodactyl Daemon", so you have the option to set it to whatever you want, regardless if it ends in Daemon or not?

2021-04-04 15:48 UTC, FoksVHox commented
> Shouldn't the default be "Pterodactyl Daemon", so you have the option to set it to whatever you want, regardless if it ends in Daemon or not?

I wouldnt say so as Wings is a daemon